name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./backend/ -t wrqng/notes-app-backend:${{ github.sha }}
          docker build ./frontend/ -t wrqng/notes-app-frontend:${{ github.sha }}
      - name: push image to docker hub
        run: |
          docker login -u wrqng -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push wrqng/notes-app-backend:${{ github.sha }}
          docker push wrqng/notes-app-frontend:${{ github.sha }}

          
      - name: Checkout infra-repo and update tag
        run: |
          git clone https://x-access-token:${{ secrets.INFRA_REPO_TOKEN }}@github.com/wrQQng/argocdtry.git
          cd infra-repo
          sed -i 's|tag: .*|tag: "${{ github.sha }}"|' my-chart/values.yaml
          git config user.email "cd@wrqng.com"
          git config user.name "CD Bot"
          git add my-chart/values.yaml
          git commit -m "chore: update backend image tag to ${{ github.sha }}"
          git push